# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test cases

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Run Test-Cases
        run: npm test
        env:
          BARCHIVE_CLIENT_ID: ${{env.BARCHIVE_CLIENT_ID}}
          BARCHIVE_SECRET_KEY: ${{env.BARCHIVE_SECRET_KEY}}

          INVALID_CLIENT_ID: ${{env.INVALID_CLIENT_ID}}
          INVALID_SECRET_KEY: ${{env.INVALID_SECRET_KEY}}

          INVALID_AUTH_TOKEN: ${{env.INVALID_AUTH_TOKEN}}

          ERC_CLIENT_ID: ${{env.ERC_CLIENT_ID}}
          ERC_SECRET_KEY: ${{env.ERC_SECRET_KEY}}

          TOKEN_ENGINE_CLIENT_ID: ${{env.TOKEN_ENGINE_CLIENT_ID}}
          TOKEN_ENGINE_SECRET_KEY: ${{env.TOKEN_ENGINE_SECRET_KEY}}

          CHAIN_CODE_20: ${{env.CHAIN_CODE_20}}
          CHANNEL_20: ${{env.CHANNEL_20}}

          CHAIN_CODE_721: ${{env.CHAIN_CODE_721}}
          CHANNEL_721: ${{env.CHANNEL_721}}

          CHAIN_CODE_1155: ${{env.CHAIN_CODE_1155}}
          CHANNEL_1155: ${{env.CHANNEL_1155}}

